export EDITOR=nvim
export ZSH="/Users/connor.george/.oh-my-zsh"

ZSH_THEME="afowler"
HIST_STAMPS="mm/dd/yyyy"	
DEFAULT_USER=$USER	
HISTFILE=~/.zsh_history
export HISTTIMEFORMAT="%h/%d - %H:%M:%S "

alias gp="git push"
alias gap="git add -p"
alias gs="git switch"
alias gpr="git pull --rebase"
alias cat="ccat"
alias ll="ls -a"
alias n="nvim"
alias vim="nvim"
alias vi="nvim"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/connor.george/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/connor.george/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/connor.george/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/connor.george/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# aws completer
export PATH=/Users/connor.george/miniconda3/bin/aws_completer:$PATH
eval "$(pyenv init -)"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR="vim"
else
  export EDITOR='vi'
fi
